### ISSUE TITLE
Snoopy Fails to build from source with gcc-7

### ISSUE THREAD

**Issue by MarcosFouces** [a2o/snoopy#123]
## Checklist before I submit this issue report

I confirm that:
- [ *] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [* ] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [* ] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [ *] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

(replace 'FILLIN' with actual values from your environment)

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | amd64            | x86 is not supported anymore     |
| Linux distribution:                 | Debian            | |
| Distribution version:               | Buster (testing)            | |
| Snoopy version:                     | 2.4.6           | |
| Snoopy config file was used:        | yes   | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | no   | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

This is not a runtime issue but a compile time one.

## Issue description - Describe the problem you are having

Snoopy fails to build from source when trying to build it with gcc-7. It is now the default compiler version on Debian and the package will be removed on 20 august if a fix is not provided.

Here you can check the build log obtained with the previous version of snoopy packaged for Debian (2.3.1):
http://people.debian.org/~doko/logs/gcc7-20170126/snoopy_2.3.1-2_unstable_gcc7.log

You can also check the Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853664

I also attached the build log with 2.4.6 version i obtained on my machine.

## Expected result

A succesful build! :-)

## Actual result

FTBS (attached the build log i obtained on my machine).

## Steps to reproduce

Just us gcc-7 instead of the version you currently use to build Snoopy (surely gcc-6)
[snoopy_gcc7-log.txt](https://github.com/a2o/snoopy/files/1206198/snoopy_gcc7-log.txt)

Thanks for your time.
Greetings.

**Comment by lukas227** [comment]
Just for reference: this problem is fixed by pull request #122 .

**Comment by ageis** [comment]
Also failed to build with GCC 7.3.0:
```cmdline.c: In function 'snoopy_datasource_cmdline':
cmdline.c:71:79: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
     for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
                                                                               ^~
cmdline.c:71:30: note: did you mean to dereference the pointer?
     for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
                              ^
```

**Comment by bostjan** [comment]
Fixed by merging pull request #122. This will be included in the next release.
